name: ihate
description: My Cool Website.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  lottie: ^2.7.0
  url_launcher: ^6.2.0
  flutter_svg: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottiefiles/
    - assets/svgs/

  fonts:
    - family: Caveat
      fonts:
        - asset: assets/fonts/caveat/Caveat-Bold.ttf
          weight: 700
    - family: Jetbrains-Mono
      fonts:
        - asset: assets/fonts/jetbrains-mono/JetBrainsMono-Light.ttf
          weight: 300
